package com.crispytwig.dwellers.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class BeetleAnimation {
    public static final AnimationDefinition WALK = AnimationDefinition.Builder.withLength(1f).looping()
            .addAnimation("left_front_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -36.41f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, -42.01f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, -44.75f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -44.45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, -41.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, -34.97f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, -26.45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, -16.13f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, -4.7f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 7.04f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 18.3f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, 28.32f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 36.41f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 42.01f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, 44.75f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, 44.45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, 41.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, 34.97f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, 26.45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, 16.13f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 4.7f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, -7.04f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, -18.3f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, -28.32f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -36.41f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_back_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, -24.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, -33.44f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -40.1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, -44.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, -44.94f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, -42.8f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, -37.74f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, -30.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, -20.43f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -9.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, 2.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 24.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, 33.44f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, 40.1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, 44.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, 44.94f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, 42.8f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, 37.74f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 30.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, 20.43f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, 9.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, -2.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("left_middle_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 43.47f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 38.97f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 31.82f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, 11.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, -11.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, -31.82f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -38.97f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, -43.47f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, -45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, -43.47f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, -38.97f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, -31.82f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, -11.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, 11.65f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 22.5f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, 31.82f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, 38.97f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, 43.47f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_front_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 2.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, -9.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -20.43f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, -30.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, -37.74f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, -42.8f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, -44.94f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, -44.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, -40.1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -33.44f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, -24.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, -13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, -2.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, 9.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, 20.43f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, 30.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, 37.74f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, 42.8f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, 44.94f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 44.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, 40.1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, 33.44f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, 24.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_back_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, -24.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, -33.44f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -40.1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, -44.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, -44.94f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, -42.8f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, -37.74f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, -30.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, -20.43f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -9.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, 2.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 24.51f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, 33.44f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, 40.1f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, 44.02f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, 44.94f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, 42.8f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, 37.74f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 30.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, 20.43f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, 9.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, -2.36f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -13.91f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("right_middle_leg",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -36.41f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, -42.01f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, -44.75f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -44.45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, -41.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, -34.97f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, -26.45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, -16.13f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, -4.7f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 7.04f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 18.3f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, 28.32f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 36.41f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 42.01f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, 44.75f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, 44.45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, 41.11f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, 34.97f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, 26.45f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, 16.13f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 4.7f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, -7.04f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, -18.3f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, -28.32f, 0f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -36.41f, 0f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("head",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 1.62f, 1.18f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, 1.26f, 1.55f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0.81f, 1.83f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0.31f, 1.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, -0.21f, 1.99f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, -0.72f, 1.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, -1.18f, 1.62f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, -1.55f, 1.26f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, -1.83f, 0.81f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, -1.98f, 0.31f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, -1.99f, -0.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, -1.87f, -0.72f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, -1.62f, -1.18f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, -1.26f, -1.55f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, -0.81f, -1.83f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, -0.31f, -1.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, 0.21f, -1.99f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, 0.72f, -1.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, 1.18f, -1.62f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, 1.55f, -1.26f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, 1.83f, -0.81f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, 1.98f, -0.31f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, 1.99f, 0.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, 1.87f, 0.72f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 1.62f, 1.18f),
                                    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("body",
                    new AnimationChannel(AnimationChannel.Targets.ROTATION,
                            new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -1.62f, -1.18f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.041676664f, KeyframeAnimations.degreeVec(0f, -1.26f, -1.55f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, -0.81f, -1.83f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -0.31f, -1.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(0f, 0.21f, -1.99f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.20834331f, KeyframeAnimations.degreeVec(0f, 0.72f, -1.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.24999999999999997f, KeyframeAnimations.degreeVec(0f, 1.18f, -1.62f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.29167663f, KeyframeAnimations.degreeVec(0f, 1.55f, -1.26f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 1.83f, -0.81f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 1.98f, -0.31f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 1.99f, 0.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.45834337f, KeyframeAnimations.degreeVec(0f, 1.87f, 0.72f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 1.62f, 1.18f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5416766f, KeyframeAnimations.degreeVec(0f, 1.26f, 1.55f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.5834333f, KeyframeAnimations.degreeVec(0f, 0.81f, 1.83f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6249999999999999f, KeyframeAnimations.degreeVec(0f, 0.31f, 1.98f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.6766665f, KeyframeAnimations.degreeVec(0f, -0.21f, 1.99f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7083431f, KeyframeAnimations.degreeVec(0f, -0.72f, 1.87f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7499999999999998f, KeyframeAnimations.degreeVec(0f, -1.18f, 1.62f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.7916764f, KeyframeAnimations.degreeVec(0f, -1.55f, 1.26f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.834333f, KeyframeAnimations.degreeVec(0f, -1.83f, 0.81f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.8749999999999997f, KeyframeAnimations.degreeVec(0f, -1.98f, 0.31f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9167663f, KeyframeAnimations.degreeVec(0f, -1.99f, -0.21f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(0.9583429f, KeyframeAnimations.degreeVec(0f, -1.87f, -0.72f),
                                    AnimationChannel.Interpolations.LINEAR),
                            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -1.62f, -1.18f),
                                    AnimationChannel.Interpolations.LINEAR))).build();
}
